# Generated by Django 6.0.5 on 2026-05-30 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_provider_is_active_provider_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='is_approved',
        ),
    ]
