# Generated by Django 6.0.5 on 2026-05-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_remove_provider_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='service_type',
            field=models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('carpenter', 'Carpenter'), ('cleaning', 'Cleaning'), ('painter', 'Painter'), ('mechanic', 'Mechanic')], max_length=50),
        ),
    ]
