# Generated by Django 6.0.5 on 2026-05-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_serviceprofile_serviceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
