# Generated by Django 6.0.5 on 2026-05-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_remove_provider_password_alter_provider_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprofile',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
