# Generated by Django 6.0.5 on 2026-06-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_serviceprofile_facebook_serviceprofile_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='service_type',
        ),
        migrations.AddField(
            model_name='serviceprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='serviceprofile',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceprofile',
            name='service_type',
            field=models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('carpenter', 'Carpenter'), ('cleaning', 'Cleaning'), ('painter', 'Painter'), ('mechanic', 'Mechanic')], default='electrician', max_length=50),
        ),
    ]
