# Generated by Django 6.0.5 on 2026-06-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_remove_provider_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprofile',
            name='service_type',
            field=models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('carpenter', 'Carpenter'), ('cleaning', 'Cleaning'), ('painter', 'Painter'), ('mechanic', 'Mechanic')], default='None', max_length=50),
        ),
    ]
