# Generated by Django 6.0.5 on 2026-06-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_alter_serviceprofile_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprofile',
            name='service_type',
            field=models.CharField(choices=[('none', 'None'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('carpenter', 'Carpenter'), ('cleaning', 'Cleaning'), ('painter', 'Painter'), ('mechanic', 'Mechanic')], default='none', max_length=50),
        ),
    ]
