# Generated by Django 6.0.5 on 2026-06-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0012_alter_serviceprofile_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprofile',
            name='latitude',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceprofile',
            name='longitude',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
