# Generated by Django 6.0.5 on 2026-05-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dealer',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
