# Generated by Django 6.0.5 on 2026-05-30 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_dealer_delete_provider'),
        ('dealers', '0005_alter_dealer_user'),
        ('providers', '0008_remove_provider_password_alter_provider_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
