# Generated by Django 6.0.5 on 2026-05-30 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_dealer_is_active_dealer_is_approved_dealer_trial_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='is_approved',
        ),
    ]
